In [2]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
import numpy as np

empty=np.empty((3,2))
print(empty)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
import numpy as np

ran=np.random.random((3,2))
print(ran)

[[0.21904582 0.59870696]
 [0.20676896 0.40972415]
 [0.63159732 0.67906018]]


In [7]:
import numpy as np

evensp=np.arange(1,25,5)
print(evensp)


[ 1  6 11 16 21]


In [18]:
import numpy as np

linesp=np.linspace(0,100,25)
print(linesp)


[  0.           4.16666667   8.33333333  12.5         16.66666667
  20.83333333  25.          29.16666667  33.33333333  37.5
  41.66666667  45.83333333  50.          54.16666667  58.33333333
  62.5         66.66666667  70.83333333  75.          79.16666667
  83.33333333  87.5         91.66666667  95.83333333 100.        ]


In [23]:
import numpy as np

fullar=np.full((3,2),5)
print(fullar)
print(fullar.shape)
print(fullar.ndim)
print(len(fullar))

[[5 5]
 [5 5]
 [5 5]]
(3, 2)
2
3


In [27]:
#Array Indexing
x = np.array([9,8,7,6,5,4,3,2,1,0]) 
print(x[:]) 

[9 8 7 6 5 4 3 2 1 0]


In [28]:
#Array Indexing
x = np.array([9,8,7,6,5,4,3,2,1,0]) 
print(x[::]) 

[9 8 7 6 5 4 3 2 1 0]


In [29]:
#Array Indexing
x = np.array([9,8,7,6,5,4,3,2,1,0]) 
print(x[::2]) 

[9 7 5 3 1]


In [30]:
#Array Indexing
x = np.array([9,8,7,6,5,4,3,2,1,0]) 
print(x[::3])

[9 6 3 0]


In [32]:
#Array Indexing
x = np.array([9,8,7,6,5,4,3,2,1,0,11]) 
print(x[-5:10]) 


[3 2 1 0]


In [34]:
x = np.array([9,8,7,6,5,4,3,2,1,0,11]) 

y=x.astype(float)
print(y)

[ 9.  8.  7.  6.  5.  4.  3.  2.  1.  0. 11.]


In [35]:
import numpy as np
a=np.array([[2,2],[3,3]])
print(a)
print(a.ndim)

[[2 2]
 [3 3]]
2


In [36]:
# Arithmetic operations using Numpy 
import numpy as np
a=np.array([[2,2],[3,3]])
print(a)
print(a.ndim)
b=np.array([[7,7],[8,8]])
print(b)
print(b.ndim)

[[2 2]
 [3 3]]
2
[[7 7]
 [8 8]]
2


In [37]:
c=a+b
print(c)

[[ 9  9]
 [11 11]]


In [38]:
d=a-b
print(d)


[[-5 -5]
 [-5 -5]]
