In [2]:
#Creating arrays in numpy 

#Using Python lists:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
#Output:
#[1 2 3 4 5]

#Using built-in functions:
import numpy as np
zeros = np.zeros(5)
print(zeros)

ones = np.ones(5)
print(ones)

rand = np.random.rand(5)
print(rand)

#Output:
#[0. 0. 0. 0. 0.]
#[1. 1. 1. 1. 1.]
#[0.84282437 0.70539582 0.82060015 0.99619884 0.65457833]


[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0.67455461 0.94118338 0.02060978 0.46084961 0.59215361]


In [3]:
#Creating a range of numbers:
import numpy as np

range_arr = np.arange(1, 6)
print(range_arr)


[1 2 3 4 5]


In [5]:
#Reshaping an array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original Array: ")
print(arr)
reshaped_arr = arr.reshape(2, 3)
print("Reshaped Array: ")
print(reshaped_arr)


Original Array: 
[1 2 3 4 5 6]
Reshaped Array: 
[[1 2 3]
 [4 5 6]]


In [6]:
#Creating an array with a specified data type:
import numpy as np
arr = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [9]:
import numpy as np

# Create a 1D array
arr1 = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Access the first element
print(arr1[0])  # Output: 1

# Access the last element
print(arr1[-1])  # Output: 5

# Access a subset of elements
print(arr1[3:8])  # Output: [2 3 4]


11
20
[14 15 16 17 18]


In [12]:
#Arithmetic operation on an array
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])

# Add the arrays
arr3 = arr1 + arr2
print(arr3)  # Output: [ 3  6  9 12 15]

# Multiply the arrays
arr4 = arr1 * arr2
print(arr4)  # Output: [ 2  8 18 32 50]

[ 3  6  9 12 15]
[ 2  8 18 32 50]


In [13]:
#apply various functions to NumPy arrays, such as sin(), cos(), exp(), etc. 
import numpy as np

# Create an array
arr1 = np.array([0, np.pi/2, np.pi])

# Apply sin() function to the array
arr2 = np.sin(arr1)
print(arr2)  # Output: [0.         1.         0.        ]

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [16]:
#Reshaping arrays:
#We can reshape a NumPy array using the reshape() function. 
#This function returns a new array with the same data but a different shape. The reshape() function can be used to convert a 1D array to a 2D array, or vice versa.

import numpy as np

# Create a 1D array
print("1D array: ")
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1)

# Reshape the array to a 2D array
print("Reshape the array to a 2D array: ")
arr2 = arr1.reshape(2, 3)
print(arr2)

# Output:
# [[1 2 3]
#  [4 5 6]]

# Reshape the array back to a 1D array
print("Reshape the array back to a 1D array")
arr3 = arr2.reshape(6)
print(arr3)  # Output: [1 2 3 4 5 6]


1D array: 
[1 2 3 4 5 6]
Reshape the array to a 2D array: 
[[1 2 3]
 [4 5 6]]
Reshape the array back to a 1D array
[1 2 3 4 5 6]


In [17]:
#Using scalars in numpy

#Scalars in NumPy refer to a single value or an element in an array. 
#Scalars can be used to perform arithmetic operations with arrays or can
#be used as an element in an array.

#To create a scalar in NumPy, we can use the numpy.array() method and 
#pass a single value as a parameter.

#an example of using scalars in NumPy:

import numpy as np

# Create a scalar with value 5
scalar = np.array(5)

# Create an array with shape (3,3) and fill it with scalar values
arr = np.full((3,3), scalar)

# Perform arithmetic operations with scalar and array
addition = arr + scalar
subtraction = arr - scalar
multiplication = arr * scalar
division = arr / scalar

# Print the resulting arrays
print("Original array:\n", arr)
print("\nAddition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nMultiplication:\n", multiplication)
print("\nDivision:\n", division)


Original array:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Multiplication:
 [[25 25 25]
 [25 25 25]
 [25 25 25]]

Division:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Indexing Arrays in numpy

#In NumPy, indexing is used to access the elements of an array. 
#Indexing allows us to retrieve a specific subset of elements from an array.

#In NumPy, indexing is similar to indexing in Python lists, but with
#additional functionality. We can index NumPy arrays using integers, 
#slices, boolean arrays, and fancy indexing.


In [18]:
#1. Indexing with integers:
#We can index a NumPy array using integers, which returns a specific 
#element at the given index. We can also use negative indexing, which 
#returns an element counting from the end of the array.


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[0])     # Output: 1
print(arr[-1])    # Output: 5

1
5


In [19]:
#2. Slicing arrays:
#We can also retrieve a subset of elements from a NumPy array using slicing. Slicing is done by specifying the start index, end index, and step size.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])   

 # Output: [2 3 4]

[2 3 4]


In [20]:
#3. Boolean indexing:
#Boolean indexing is a powerful feature in NumPy that allows us to
#select elements based on a condition. We can create a boolean array by 
#applying a condition on the original array, and use this boolean array to 
#select elements from the original array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
bool_arr = arr > 2
print(bool_arr)    # Output: [False False  True  True  True]
print(arr[bool_arr])   # Output: [3 4 5]

[False False  True  True  True]
[3 4 5]


In [21]:
#4. Fancy indexing:
#Fancy indexing refers to indexing an array using another array or a list.
#We can use fancy indexing to select a subset of elements from the original
#array in any order.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
idx = np.array([0, 3, 4])
print(arr[idx])    # Output: [1 4 5]


[1 4 5]


In [22]:
#Array Transposition in numpy

#In NumPy, transposition is the operation of interchanging rows and
#columns of an array. It can be performed using the transpose() method or 
#the T attribute.

import numpy as np

# Creating a 2D array
arr = np.array([[1, 2], [3, 4]])

# Transposing the array using transpose() method
transposed_arr = arr.transpose()

# Displaying the original and transposed arrays
print("Original Array:\n", arr)
print("Transposed Array:\n", transposed_arr)

# Transposing the array using T attribute
T_arr = arr.T

# Displaying the original and transposed arrays
print("Original Array:\n", arr)
print("Transposed Array using T attribute:\n", T_arr)


'''
Output:
Original Array:
 [[1 2]
 [3 4]]
Transposed Array:
 [[1 3]
 [2 4]]
Original Array:
 [[1 2]
 [3 4]]
Transposed Array using T attribute:
 [[1 3]
 [2 4]]
'''

Original Array:
 [[1 2]
 [3 4]]
Transposed Array:
 [[1 3]
 [2 4]]
Original Array:
 [[1 2]
 [3 4]]
Transposed Array using T attribute:
 [[1 3]
 [2 4]]


'\nOutput:\nOriginal Array:\n [[1 2]\n [3 4]]\nTransposed Array:\n [[1 3]\n [2 4]]\nOriginal Array:\n [[1 2]\n [3 4]]\nTransposed Array using T attribute:\n [[1 3]\n [2 4]]\n'

In [23]:
#transposition in NumPy for a 3-D array:

import numpy as np

# create a 3-D array
arr = np.arange(24).reshape((2, 3, 4))

# print the original array
print("Original Array:")
print(arr)

# transpose the array
transposed_arr = arr.transpose((1, 2, 0))

# print the transposed array
print("\nTransposed Array:")
print(transposed_arr)

'''#Output:
Original Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Transposed Array:
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]'''


Original Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Transposed Array:
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


'#Output:\nOriginal Array:\n[[[ 0  1  2  3]\n  [ 4  5  6  7]\n  [ 8  9 10 11]]\n\n [[12 13 14 15]\n  [16 17 18 19]\n  [20 21 22 23]]]\n\nTransposed Array:\n[[[ 0 12]\n  [ 1 13]\n  [ 2 14]\n  [ 3 15]]\n\n [[ 4 16]\n  [ 5 17]\n  [ 6 18]\n  [ 7 19]]\n\n [[ 8 20]\n  [ 9 21]\n  [10 22]\n  [11 23]]]'

In [ ]:
'''#commonly used ufunc in NumPy are:
np.add()
np.subtract()
np.multiply()
np.divide()
np.power()
np.sqrt()
np.exp()
np.log()
np.sin()
np.cos()
np.tan()
np.arcsin()
np.arccos()
np.arctan()
np.sum()
np.mean()
np.std()
np.min()
np.max()'''

In [24]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# add the two arrays
add_arr = np.add(arr1, arr2)
print(add_arr) # [6 6 6 6 6]

# multiply the two arrays
mul_arr = np.multiply(arr1, arr2)
print(mul_arr) # [5 8 9 8 5]

# calculate the square root of each element in arr1
sqrt_arr = np.sqrt(arr1)
print(sqrt_arr) # [1.         1.41421356 1.73205081 2.         2.23606798]

# calculate the mean of elements in arr2
mean_arr = np.mean(arr2)
print(mean_arr) # 3.0


[6 6 6 6 6]
[5 8 9 8 5]
[1.         1.41421356 1.73205081 2.         2.23606798]
3.0


In [32]:
#Array Input and Output in numpy

'''NumPy provides several functions to save and load arrays from disk. 
This is very useful for large data sets that need to be reused multiple 
times.

The most commonly used file formats for storing NumPy arrays 
are .npy and .npz. The .npy format stores a single NumPy array in
a binary format, while the .npz format stores multiple NumPy arrays 
in a ZIP archive.

examples of how to use the array input and output functions in NumPy:
'''

In [34]:
#Saving an array to disk
import numpy as np
# create an array
a = np.array([1, 2, 3, 4, 5])

# save the array to disk in binary format
np.save('my_array', a)
print("Array saved to disk successfully...")

Array saved to disk successfully...


In [35]:
#Loading an array from disk
import numpy as np

# load the array from disk
a = np.load('my_array.npy')

print(a)
# Output: [1 2 3 4 5]


[1 2 3 4 5]


In [37]:
#Saving multiple arrays to disk
import numpy as np

# create some arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

# save the arrays to disk in a ZIP archive
np.savez('my_arrays.npz', a=a, b=b)
print("multiple arrays to disk in ZIP archive...")

multiple arrays to disk in ZIP archive...


In [38]:
# load the arrays from disk
arrays = np.load('my_arrays.npz')

# access the arrays by name
a = arrays['a']
b = arrays['b']

print(a)
# Output: [1 2 3 4 5]

print(b)
# Output: [ 6  7  8  9 10]

[1 2 3 4 5]
[ 6  7  8  9 10]
